// get ships
export const GET_ALL_STARSHIPS_DATA = 'GET_ALL_STARSHIPS_DATA';
export const GET_ALL_STARSHIPS_DATA_SUCCESS = 'GET_ALL_STARSHIPS_DATA_SUCCESS';
export const GET_ALL_STARSHIPS_DATA_FAIL = 'GET_ALL_STARSHIPS_DATA_FAIL';
// get one ship
export const GET_ONE_STARSHIPS_DATA = 'GET_ONE_STARSHIPS_DATA';
export const GET_ONE_STARSHIPS_DATA_SUCCESS = 'GET_ONE_STARSHIPS_DATA_SUCCESS';
export const GET_ONE_STARSHIPS_DATA_FAIL = 'GET_ONE_STARSHIPS_DATA_FAIL';
// searching ships
export const SEARCH_STARSHIP_DATA = 'SEARCH_STARSHIP_DATA';
export const SEARCH_STARSHIP_DATA_SUCCESS = 'SEARCH_STARSHIP_DATA_SUCCESS';
export const SEARCH_STARSHIP_DATA_FAIL = 'SEARCH_STARSHIP_DATA_FAIL';